name: Docker builds

on:
  push:
    branches: ['*']
  pull_request:
    branches: [master]
  schedule:
    # At 01:18 every Thursday. Details in https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
    - cron: '18 1 * * 4'

env:
  DOCKER_IMAGE: 'ghcr.io/${{ github.repository }}'
  PLATFORMS: linux/amd64

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker meta
        id: image_meta
        uses: docker/metadata-action@v5
        with:
          context: "git"
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=sha
            type=raw,latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context:     .
          sbom:        true
          provenance:  mode=max
          platforms:   ${{ env.PLATFORMS }}
          pull:        true
          push:        true
          tags:        ${{ steps.image_meta.outputs.tags }}
          labels:      ${{ steps.image_meta.outputs.labels }}
          annotations: ${{ steps.image_meta.outputs.annotations }}
          cache-from:  type=gha
          cache-to:    type=gha,mode=max
          build-args: |
            NODE_ENV=production
            VERSION=${{ github.ref_name }}
            COMMIT_SHA=${{ github.sha }}
